### ISSUE TITLE
SHA command ATECC608A

### ISSUE THREAD

**Issue by Grifenfer** [f-secure-foundry/armoryctl#1]
Hello, I am trying to use this to make the ATECC608A to execute the SHA command. I send a start command then an update and finally a end command, like written in the datasheet of the chip. But the update command fails and the error is a parse error. But I don't see what I am doing wrong. 

Could you help me ? 

In attached files you will find the modifications I made for the atecc608.go file

I send a start command first: Param1 = 0x00
                                               Param2 = 0x00, 0x00 (byte 0, byte 1)
Then I send an update command : Param1 = 0x01
                                                        Param2 = 0x00, 0x00 
                                                        Data = 32 bytes randomly generated
Finally I send an end command : Param1 = 0xC2
                                                     Param2 = 0x00, 0x00

When I print the result of the start command, it prints : 0x00%!(EXTRA string=) and when I try to use the command to read the context it responds with a parse error to (after the sha_start). 
[atecc608_moified.zip](https://github.com/f-secure-foundry/armoryctl/files/6990705/atecc608_moified.zip)

**Comment by abarisani** [comment]
Your example doesn't compile and has some issues, here's a better one:

```go
func TestSHA() (res string, err error){
	sha := byte(0x47)

	// initialize
	if _, err = ExecuteCmd(sha, [1]byte{0x00}, [2]byte{0x00,0x00}, nil, true); err != nil {
		return "", fmt.Errorf("init error, %v", err)
	}

	buf := make([]byte, 64)
        cnt := byte(len(buf))

	// update
	if _, err = ExecuteCmd(sha, [1]byte{0x01}, [2]byte{cnt, 0x00}, buf, true); err != nil {
		return "", fmt.Errorf("update error, %v", err)
	}

	// finalize
	h, err := ExecuteCmd(sha, [1]byte{0x02}, [2]byte{0x00,0x00}, nil, true)

	if err != nil {
		return "", fmt.Errorf("end error, %v", err)
	}

	return fmt.Sprintf("got %d bytes: %x", len(h), h), nil
}
```

However this still doesn't work and I have yet to figure out why as the resulting packets look correct to me:

```
# initialize (len:0x07, cmd:0x47, mode:0x00, msgLen:0x0000)
cmd: 07470000002e85
# update with 64 bytes of zero (len:0x07 + 0x40, cmd:0x47, mode:0x01, msgLen:0x4000)
cmd: 4747014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007ed2
error: update error, parse error
```

**Comment by Grifenfer** [comment]
Thank you for your response and the modification of the code. 

Do we have to send the length of the data we use in the update command ? Because it is not really clear on the datasheet and I saw on the microchip forum (https://www.microchip.com/forums/m1166562.aspx) that someone don't do it.

**Comment by abarisani** [comment]
As far as I can see the length must always be sent and I don't see any reason why it shouldn't be like that. The device must know the total size of the packet as well as the size of the message within the update.

**Comment by abarisani** [comment]
At this point I am leaning towards the fact that the `SHA` command requires a configured device to work, even when not computing an HMAC, as the packets seems all correct to me (my test ATECC is not configured/locked in any way).

**Comment by Grifenfer** [comment]
I configured and locked it. And I still have this error.  The self_test command, given in armoryctl, returns a success for the SHA command. 

In the datasheet it is not written that the chip must be configured or locked in any particular way (or am I wrong ?).

**Comment by abarisani** [comment]
The datasheet does not say that, you are correct, I am merely speculating given that I don't see any other explanation. However you cleared that out with your test, so the answer must lie elsewhere.

**Comment by Grifenfer** [comment]
However, I have a small doubt about the test. In the file atecc608.go, in the Test map (line 72), you have matched the code 0x20 to RNG but on the datasheet it matches the code for the SHA command (Bit 5: If 1, test the SHA function). 

Is there any reason for that ?

**Comment by abarisani** [comment]
The ATECC608A datasheet I have (2018, "Datasheet Preliminary") says "Bit 5: If 1, test the RNG, including both the DRBG and NRBG....", there is no mention of SHA in the self test. Regardless of this I don't see how `SelfTest` result interpretation can affect `SHA` operation.

**Comment by Grifenfer** [comment]
I only found the 2017, "Datasheet Preliminary" online. This is maybe why I have some issues.

How can I have the 2018 dataseheet.

**Comment by abarisani** [comment]
The datasheet is available under NDA from Microchip.

**Comment by Grifenfer** [comment]
I will get it and return here later then.

**Comment by abarisani** [comment]
The 608A is designed to be 508A compatible with few exceptions, therefore the full 608A datasheet should not be required to get `SHA` going.

This [driver](https://github.com/luciodj/PIC-IOT_AirQuality.X/blob/master/mcc_generated_files/cryptoauthlib/lib/basic/atca_basic_sha.c) gives an overview of the compatibility across P/Ns.

This [Application Note](http://ww1.microchip.com/downloads/en/Appnotes/00002589A.pdf) also covers P/Ns differences.

**Comment by abarisani** [comment]
I found the issue and I am working on a patch. Stay tuned.

**Comment by abarisani** [comment]
The fix is at https://github.com/f-secure-foundry/armoryctl/commit/4b7296d9ca6ea7eca959f88ef0894a0af28192d1

Rather than patching the library itself, here's sample usage as an import that demonstrates SHA command use:

```go
package main

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"log"
	"time"

	"github.com/f-secure-foundry/armoryctl/atecc608"
)

func main() {
	op := atecc608.Cmd["SHA"]

	buf := make([]byte, sha256.BlockSize)
	cnt := byte(len(buf))

	if _, err := rand.Read(buf); err != nil {
		log.Fatalf("error: %v", err)
	}

	log.Printf("executing sha256(%x)\n", buf)

	atecc608.CmdExecutionTime = 1 * time.Millisecond

	// initialize
	if _, err := atecc608.ExecuteCmd(op, [1]byte{0x00}, [2]byte{0x00, 0x00}, nil, true); err != nil {
		log.Fatalf("init error, %v", err)
	}

	// update
	if _, err := atecc608.ExecuteCmd(op, [1]byte{0x01}, [2]byte{cnt, 0x00}, buf, true); err != nil {
		log.Fatalf("update error, %v", err)
	}

	// finalize
	h, err := atecc608.ExecuteCmd(op, [1]byte{0x02}, [2]byte{0x00, 0x00}, nil, true)

	if err != nil {
		log.Fatalf("end error, %v", err)
	}

	ref := sha256.Sum256(buf)

	if !bytes.Equal(h, ref[:]) {
		log.Printf("mismatch (%x != %x)\n", h, ref)
	} else {
		log.Printf("success (%x)\n", h)
	}
}
```

**Comment by Grifenfer** [comment]
Thank you for your rapid responses and your example. So the problem was about the CmdExecutionTime ?

**Comment by abarisani** [comment]
No, the problem was that we were sleeping after each command, rather than idling, and that caused the internal temporary registers to be cleared, see [here](https://github.com/f-secure-foundry/armoryctl/commit/4b7296d9ca6ea7eca959f88ef0894a0af28192d1#diff-79e7ed6f3bae6f4b8e3507cfd2b5005cf50709299a778f0c910d9165416aaaecL192).
